project:
  type: website
  output-dir: docs

website:
  title: "CSCI 1010 [Fall 2023]"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Getting Started"
        menu:
          - href: install-editor.qmd
          - href: "homework.qmd#launch-jupyter"
            text: "Launch a Jupyter Server"
          - href: "homework.qmd#work-with-HW.ipynb"
            text: "Working with HW .ipynb files"
      - about.qmd
      - schedule.qmd
      - policies.qmd
      - instructor.qmd
    search: true

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



