project:
  type: website
  output-dir: docs

website:
  title: "CSCI 1010 [Fall 2023]"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - schedule.qmd
      - policies.qmd
      - instructor.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true



