# Student guest speakers

## Marlee Alvino
<div id="marlee-alvino"></div>

**Marlee** is a senior majoring in computer science with a minor in statistics and, during her time here, she has done a little of just about everything. That includes: being a TA, doing research, mentoring first year students, having internships, and leading student organizations. It’s safe to say there’s a space here for everyone, and she is excited to share it with you!

**Email**: [marlenaalvino@gwmail.gwu.edu](marlenaalvino@gwmail.gwu.edu)

## Samantha Kusner
<div id="samantha-kusner"></div>
**Sam** is a senior majoring in computer science. During her time at GW, she’s had the opportunity to be on the leadership team for few different organizations, foster a positive learning environment as an LA and UTA, and speak to students like you who are just joining the CS community here. Outside of school, she’s had a few internships which have helped her get a better understanding of what possibilities are out there! She’s looking forward to sharing some of her experience with you.

**Email**: [samkusner430@gwmail.gwu.edu](samkusner430@gwmail.gwu.edu)

<br><br>
<footer>
  <p><small><small><small><small>This is a Quarto website. To learn more about Quarto websites visit <https://quarto.org/docs/websites>.<br>
  Author: Kartik Bulusu<br>
  Contact: <a href="mailto:bulusu@gwu.edu">bulusu</a><br>
  &copy; 2023 All rights reserved</small></small></small></small></p>
</footer>